### ISSUE TITLE
implements() broken in 2.6

### ISSUE THREAD

**Issue by icemac** [zopefoundation/grokcore.component#6]
Code example:
```
>>> import grokcore.component
>>> import zope.interface
>>> class I(zope.interface.Interface): pass
...
>>> class A(object):
...     grokcore.component.implements(I)
...
>>> I.providedBy(A())
False
>>> class B(object):
...     zope.interface.implements(I)
...
>>> I.providedBy(B())
True
```

The Interface `I` is not provided by instances of `A` which is surprising.
This change seems to be introduced in version 2.6 and breaks compatibility with previous versions.

Expectation: The behavior of `implements()` should not change on the 2.x branch. If it is not possible to keep the compatibility this change should appear in a version 3.x.

**Comment by thefunny42** [comment]
Yes there is a behaviour change. grokcore.implements still works like it is used, including in Python 3, but  only after the grokker and/or zcml handlers are executed. So you need to make sure that:
- you always grok your packages (obviously the interpreter does not do it),
- make sure you do use them within custom directives. In that case, you need to use the implementer class decorator instead that is compatible with both Python 2 and Python 3.

I did it in a large codebase, and the impact into migrating this was limited. And that is a nice way forward to moving your code to Python 3.

**Comment by icemac** [comment]
We have a large Zope 2 project where Python 3 currently does not matter. We use there a mixture of grok and registration via ZCML. Sometimes the base class is a `grokcore.compoment.baseclass()` and some children are registered via grok others via ZCML. So the change for `implements` hurts a bit.

As it seems a bit too late to push this behavioral change to a 3.x release of this package I'd like to port my `multiple-exclude` branch to grokcore.component 2.5 to avoid the change of `implements` for now.
